import pygame

# Screen constants
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Colors
SKY_BLUE = (135, 206, 250)

# Event IDs
ADDENEMY = pygame.USEREVENT + 1
ADDCLOUD = pygame.USEREVENT + 2
LEVELSCENE = pygame.USEREVENT + 3
OUTROSCENE = pygame.USEREVENT + 4
INTROSCENE = pygame.USEREVENT + 5
